// This file is auto-generated by @hey-api/openapi-ts

/**
 * AssetPresignedDownloadResponse
 */
export type AssetPresignedDownloadResponse = {
    asset: AssetPublic;
    /**
     * Download Url
     */
    download_url: string;
    /**
     * Expires In
     */
    expires_in: number;
};

/**
 * AssetPresignedUploadRequest
 */
export type AssetPresignedUploadRequest = {
    /**
     * File Name
     */
    file_name: string;
    /**
     * Content Type
     */
    content_type: string;
    /**
     * Size
     */
    size: number;
};

/**
 * AssetPresignedUploadResponse
 */
export type AssetPresignedUploadResponse = {
    asset: AssetPublic;
    /**
     * Upload Url
     */
    upload_url: string;
    /**
     * Method
     */
    method?: string;
    /**
     * Expires In
     */
    expires_in: number;
    /**
     * Required Headers
     */
    required_headers: {
        [key: string]: string;
    };
};

/**
 * AssetPublic
 */
export type AssetPublic = {
    /**
     * File Name
     */
    file_name: string;
    /**
     * Content Type
     */
    content_type: string;
    /**
     * Size
     */
    size: number;
    /**
     * Id
     */
    id: string;
    /**
     * Owner Id
     */
    owner_id: string;
    /**
     * Object Key
     */
    object_key: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * AssetUpdate
 */
export type AssetUpdate = {
    /**
     * File Name
     */
    file_name?: string | null;
};

/**
 * Body_login_login_access_token_post_api_v1_login_access_token
 */
export type BodyLoginLoginAccessTokenPostApiV1LoginAccessToken = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * ItemCreate
 */
export type ItemCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ItemPublic
 */
export type ItemPublic = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Owner Id
     */
    owner_id: string;
};

/**
 * ItemUpdate
 */
export type ItemUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * NewPassword
 */
export type NewPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * PrivateUserCreate
 * Schema for creating users via private API.
 *
 * Attributes:
 * email: User's email address.
 * password: User's password.
 * full_name: User's full name.
 * is_verified: Whether the user is verified (unused currently).
 */
export type PrivateUserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Is Verified
     */
    is_verified?: boolean;
};

/**
 * RefineErrorResponse
 * OpenAPI-visible error envelope matching Refine's `HttpError` shape.
 */
export type RefineErrorResponse = {
    /**
     * Message
     */
    message: string;
    /**
     * Statuscode
     */
    statusCode: number;
    /**
     * Errors
     */
    errors?: {
        [key: string]: Array<string>;
    } | null;
    /**
     * Detail
     */
    detail?: unknown | null;
    /**
     * Code
     */
    code?: string | null;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Id
     */
    id: string;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name?: string | null;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password?: string | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

export type LoginLoginAccessTokenPostApiV1LoginAccessTokenData = {
    body: BodyLoginLoginAccessTokenPostApiV1LoginAccessToken;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type LoginLoginAccessTokenPostApiV1LoginAccessTokenErrors = {
    /**
     * Bad Request
     */
    400: RefineErrorResponse;
    /**
     * Unauthorized
     */
    401: RefineErrorResponse;
    /**
     * Forbidden
     */
    403: RefineErrorResponse;
    /**
     * Not Found
     */
    404: RefineErrorResponse;
    /**
     * Conflict
     */
    409: RefineErrorResponse;
    /**
     * Validation Error
     */
    422: RefineErrorResponse;
    /**
     * Internal Server Error
     */
    500: RefineErrorResponse;
    /**
     * Service Unavailable
     */
    503: RefineErrorResponse;
};

export type LoginLoginAccessTokenPostApiV1LoginAccessTokenError = LoginLoginAccessTokenPostApiV1LoginAccessTokenErrors[keyof LoginLoginAccessTokenPostApiV1LoginAccessTokenErrors];

export type LoginLoginAccessTokenPostApiV1LoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LoginLoginAccessTokenPostApiV1LoginAccessTokenResponse = LoginLoginAccessTokenPostApiV1LoginAccessTokenResponses[keyof LoginLoginAccessTokenPostApiV1LoginAccessTokenResponses];

export type LoginTestTokenPostApiV1LoginTestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type LoginTestTokenPostApiV1LoginTestTokenErrors = {
    /**
     * Bad Request
     */
    400: RefineErrorResponse;
    /**
     * Unauthorized
     */
    401: RefineErrorResponse;
    /**
     * Forbidden
     */
    403: RefineErrorResponse;
    /**
     * Not Found
     */
    404: RefineErrorResponse;
    /**
     * Conflict
     */
    409: RefineErrorResponse;
    /**
     * Validation Error
     */
    422: RefineErrorResponse;
    /**
     * Internal Server Error
     */
    500: RefineErrorResponse;
    /**
     * Service Unavailable
     */
    503: RefineErrorResponse;
};

export type LoginTestTokenPostApiV1LoginTestTokenError = LoginTestTokenPostApiV1LoginTestTokenErrors[keyof LoginTestTokenPostApiV1LoginTestTokenErrors];

export type LoginTestTokenPostApiV1LoginTestTokenResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type LoginTestTokenPostApiV1LoginTestTokenResponse = LoginTestTokenPostApiV1LoginTestTokenResponses[keyof LoginTestTokenPostApiV1LoginTestTokenResponses];

export type LoginRecoverPasswordPostApiV1PasswordRecoveryEmailData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery/{email}';
};

export type LoginRecoverPasswordPostApiV1PasswordRecoveryEmailErrors = {
    /**
     * Bad Request
     */
    400: RefineErrorResponse;
    /**
     * Unauthorized
     */
    401: RefineErrorResponse;
    /**
     * Forbidden
     */
    403: RefineErrorResponse;
    /**
     * Not Found
     */
    404: RefineErrorResponse;
    /**
     * Conflict
     */
    409: RefineErrorResponse;
    /**
     * Validation Error
     */
    422: RefineErrorResponse;
    /**
     * Internal Server Error
     */
    500: RefineErrorResponse;
    /**
     * Service Unavailable
     */
    503: RefineErrorResponse;
};

export type LoginRecoverPasswordPostApiV1PasswordRecoveryEmailError = LoginRecoverPasswordPostApiV1PasswordRecoveryEmailErrors[keyof LoginRecoverPasswordPostApiV1PasswordRecoveryEmailErrors];

export type LoginRecoverPasswordPostApiV1PasswordRecoveryEmailResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type LoginRecoverPasswordPostApiV1PasswordRecoveryEmailResponse = LoginRecoverPasswordPostApiV1PasswordRecoveryEmailResponses[keyof LoginRecoverPasswordPostApiV1PasswordRecoveryEmailResponses];

export type LoginResetPasswordPostApiV1ResetPasswordData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/api/v1/reset-password/';
};

export type LoginResetPasswordPostApiV1ResetPasswordErrors = {
    /**
     * Bad Request
     */
    400: RefineErrorResponse;
    /**
     * Unauthorized
     */
    401: RefineErrorResponse;
    /**
     * Forbidden
     */
    403: RefineErrorResponse;
    /**
     * Not Found
     */
    404: RefineErrorResponse;
    /**
     * Conflict
     */
    409: RefineErrorResponse;
    /**
     * Validation Error
     */
    422: RefineErrorResponse;
    /**
     * Internal Server Error
     */
    500: RefineErrorResponse;
    /**
     * Service Unavailable
     */
    503: RefineErrorResponse;
};

export type LoginResetPasswordPostApiV1ResetPasswordError = LoginResetPasswordPostApiV1ResetPasswordErrors[keyof LoginResetPasswordPostApiV1ResetPasswordErrors];

export type LoginResetPasswordPostApiV1ResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type LoginResetPasswordPostApiV1ResetPasswordResponse = LoginResetPasswordPostApiV1ResetPasswordResponses[keyof LoginResetPasswordPostApiV1ResetPasswordResponses];

export type LoginRecoverPasswordHtmlContentPostApiV1PasswordRecoveryHtmlContentEmailData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery-html-content/{email}';
};

export type LoginRecoverPasswordHtmlContentPostApiV1PasswordRecoveryHtmlContentEmailErrors = {
    /**
     * Bad Request
     */
    400: RefineErrorResponse;
    /**
     * Unauthorized
     */
    401: RefineErrorResponse;
    /**
     * Forbidden
     */
    403: RefineErrorResponse;
    /**
     * Not Found
     */
    404: RefineErrorResponse;
    /**
     * Conflict
     */
    409: RefineErrorResponse;
    /**
     * Validation Error
     */
    422: RefineErrorResponse;
    /**
     * Internal Server Error
     */
    500: RefineErrorResponse;
    /**
     * Service Unavailable
     */
    503: RefineErrorResponse;
};

export type LoginRecoverPasswordHtmlContentPostApiV1PasswordRecoveryHtmlContentEmailError = LoginRecoverPasswordHtmlContentPostApiV1PasswordRecoveryHtmlContentEmailErrors[keyof LoginRecoverPasswordHtmlContentPostApiV1PasswordRecoveryHtmlContentEmailErrors];

export type LoginRecoverPasswordHtmlContentPostApiV1PasswordRecoveryHtmlContentEmailResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type LoginRecoverPasswordHtmlContentPostApiV1PasswordRecoveryHtmlContentEmailResponse = LoginRecoverPasswordHtmlContentPostApiV1PasswordRecoveryHtmlContentEmailResponses[keyof LoginRecoverPasswordHtmlContentPostApiV1PasswordRecoveryHtmlContentEmailResponses];

export type UsersReadUsersGetApiV1UsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         *  Start
         */
        _start?: number | null;
        /**
         *  End
         */
        _end?: number | null;
        /**
         *  Sort
         */
        _sort?: string | null;
        /**
         *  Order
         */
        _order?: string | null;
    };
    url: '/api/v1/users/';
};

export type UsersReadUsersGetApiV1UsersErrors = {
    /**
     * Bad Request
     */
    400: RefineErrorResponse;
    /**
     * Unauthorized
     */
    401: RefineErrorResponse;
    /**
     * Forbidden
     */
    403: RefineErrorResponse;
    /**
     * Not Found
     */
    404: RefineErrorResponse;
    /**
     * Conflict
     */
    409: RefineErrorResponse;
    /**
     * Validation Error
     */
    422: RefineErrorResponse;
    /**
     * Internal Server Error
     */
    500: RefineErrorResponse;
    /**
     * Service Unavailable
     */
    503: RefineErrorResponse;
};

export type UsersReadUsersGetApiV1UsersError = UsersReadUsersGetApiV1UsersErrors[keyof UsersReadUsersGetApiV1UsersErrors];

export type UsersReadUsersGetApiV1UsersResponses = {
    /**
     * Response Users Read Users Get Api V1 Users
     * Successful Response
     */
    200: Array<UserPublic>;
};

export type UsersReadUsersGetApiV1UsersResponse = UsersReadUsersGetApiV1UsersResponses[keyof UsersReadUsersGetApiV1UsersResponses];

export type UsersCreateUserPostApiV1UsersData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type UsersCreateUserPostApiV1UsersErrors = {
    /**
     * Bad Request
     */
    400: RefineErrorResponse;
    /**
     * Unauthorized
     */
    401: RefineErrorResponse;
    /**
     * Forbidden
     */
    403: RefineErrorResponse;
    /**
     * Not Found
     */
    404: RefineErrorResponse;
    /**
     * Conflict
     */
    409: RefineErrorResponse;
    /**
     * Validation Error
     */
    422: RefineErrorResponse;
    /**
     * Internal Server Error
     */
    500: RefineErrorResponse;
    /**
     * Service Unavailable
     */
    503: RefineErrorResponse;
};

export type UsersCreateUserPostApiV1UsersError = UsersCreateUserPostApiV1UsersErrors[keyof UsersCreateUserPostApiV1UsersErrors];

export type UsersCreateUserPostApiV1UsersResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersCreateUserPostApiV1UsersResponse = UsersCreateUserPostApiV1UsersResponses[keyof UsersCreateUserPostApiV1UsersResponses];

export type UsersDeleteUserMeDeleteApiV1UsersMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersDeleteUserMeDeleteApiV1UsersMeErrors = {
    /**
     * Bad Request
     */
    400: RefineErrorResponse;
    /**
     * Unauthorized
     */
    401: RefineErrorResponse;
    /**
     * Forbidden
     */
    403: RefineErrorResponse;
    /**
     * Not Found
     */
    404: RefineErrorResponse;
    /**
     * Conflict
     */
    409: RefineErrorResponse;
    /**
     * Validation Error
     */
    422: RefineErrorResponse;
    /**
     * Internal Server Error
     */
    500: RefineErrorResponse;
    /**
     * Service Unavailable
     */
    503: RefineErrorResponse;
};

export type UsersDeleteUserMeDeleteApiV1UsersMeError = UsersDeleteUserMeDeleteApiV1UsersMeErrors[keyof UsersDeleteUserMeDeleteApiV1UsersMeErrors];

export type UsersDeleteUserMeDeleteApiV1UsersMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersDeleteUserMeDeleteApiV1UsersMeResponse = UsersDeleteUserMeDeleteApiV1UsersMeResponses[keyof UsersDeleteUserMeDeleteApiV1UsersMeResponses];

export type UsersReadUserMeGetApiV1UsersMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersReadUserMeGetApiV1UsersMeErrors = {
    /**
     * Bad Request
     */
    400: RefineErrorResponse;
    /**
     * Unauthorized
     */
    401: RefineErrorResponse;
    /**
     * Forbidden
     */
    403: RefineErrorResponse;
    /**
     * Not Found
     */
    404: RefineErrorResponse;
    /**
     * Conflict
     */
    409: RefineErrorResponse;
    /**
     * Validation Error
     */
    422: RefineErrorResponse;
    /**
     * Internal Server Error
     */
    500: RefineErrorResponse;
    /**
     * Service Unavailable
     */
    503: RefineErrorResponse;
};

export type UsersReadUserMeGetApiV1UsersMeError = UsersReadUserMeGetApiV1UsersMeErrors[keyof UsersReadUserMeGetApiV1UsersMeErrors];

export type UsersReadUserMeGetApiV1UsersMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersReadUserMeGetApiV1UsersMeResponse = UsersReadUserMeGetApiV1UsersMeResponses[keyof UsersReadUserMeGetApiV1UsersMeResponses];

export type UsersUpdateUserMePatchApiV1UsersMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersUpdateUserMePatchApiV1UsersMeErrors = {
    /**
     * Bad Request
     */
    400: RefineErrorResponse;
    /**
     * Unauthorized
     */
    401: RefineErrorResponse;
    /**
     * Forbidden
     */
    403: RefineErrorResponse;
    /**
     * Not Found
     */
    404: RefineErrorResponse;
    /**
     * Conflict
     */
    409: RefineErrorResponse;
    /**
     * Validation Error
     */
    422: RefineErrorResponse;
    /**
     * Internal Server Error
     */
    500: RefineErrorResponse;
    /**
     * Service Unavailable
     */
    503: RefineErrorResponse;
};

export type UsersUpdateUserMePatchApiV1UsersMeError = UsersUpdateUserMePatchApiV1UsersMeErrors[keyof UsersUpdateUserMePatchApiV1UsersMeErrors];

export type UsersUpdateUserMePatchApiV1UsersMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersUpdateUserMePatchApiV1UsersMeResponse = UsersUpdateUserMePatchApiV1UsersMeResponses[keyof UsersUpdateUserMePatchApiV1UsersMeResponses];

export type UsersUpdatePasswordMePatchApiV1UsersMePasswordData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type UsersUpdatePasswordMePatchApiV1UsersMePasswordErrors = {
    /**
     * Bad Request
     */
    400: RefineErrorResponse;
    /**
     * Unauthorized
     */
    401: RefineErrorResponse;
    /**
     * Forbidden
     */
    403: RefineErrorResponse;
    /**
     * Not Found
     */
    404: RefineErrorResponse;
    /**
     * Conflict
     */
    409: RefineErrorResponse;
    /**
     * Validation Error
     */
    422: RefineErrorResponse;
    /**
     * Internal Server Error
     */
    500: RefineErrorResponse;
    /**
     * Service Unavailable
     */
    503: RefineErrorResponse;
};

export type UsersUpdatePasswordMePatchApiV1UsersMePasswordError = UsersUpdatePasswordMePatchApiV1UsersMePasswordErrors[keyof UsersUpdatePasswordMePatchApiV1UsersMePasswordErrors];

export type UsersUpdatePasswordMePatchApiV1UsersMePasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersUpdatePasswordMePatchApiV1UsersMePasswordResponse = UsersUpdatePasswordMePatchApiV1UsersMePasswordResponses[keyof UsersUpdatePasswordMePatchApiV1UsersMePasswordResponses];

export type UsersRegisterUserPostApiV1UsersSignupData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/users/signup';
};

export type UsersRegisterUserPostApiV1UsersSignupErrors = {
    /**
     * Bad Request
     */
    400: RefineErrorResponse;
    /**
     * Unauthorized
     */
    401: RefineErrorResponse;
    /**
     * Forbidden
     */
    403: RefineErrorResponse;
    /**
     * Not Found
     */
    404: RefineErrorResponse;
    /**
     * Conflict
     */
    409: RefineErrorResponse;
    /**
     * Validation Error
     */
    422: RefineErrorResponse;
    /**
     * Internal Server Error
     */
    500: RefineErrorResponse;
    /**
     * Service Unavailable
     */
    503: RefineErrorResponse;
};

export type UsersRegisterUserPostApiV1UsersSignupError = UsersRegisterUserPostApiV1UsersSignupErrors[keyof UsersRegisterUserPostApiV1UsersSignupErrors];

export type UsersRegisterUserPostApiV1UsersSignupResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersRegisterUserPostApiV1UsersSignupResponse = UsersRegisterUserPostApiV1UsersSignupResponses[keyof UsersRegisterUserPostApiV1UsersSignupResponses];

export type UsersDeleteUserDeleteApiV1UsersUserIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersDeleteUserDeleteApiV1UsersUserIdErrors = {
    /**
     * Bad Request
     */
    400: RefineErrorResponse;
    /**
     * Unauthorized
     */
    401: RefineErrorResponse;
    /**
     * Forbidden
     */
    403: RefineErrorResponse;
    /**
     * Not Found
     */
    404: RefineErrorResponse;
    /**
     * Conflict
     */
    409: RefineErrorResponse;
    /**
     * Validation Error
     */
    422: RefineErrorResponse;
    /**
     * Internal Server Error
     */
    500: RefineErrorResponse;
    /**
     * Service Unavailable
     */
    503: RefineErrorResponse;
};

export type UsersDeleteUserDeleteApiV1UsersUserIdError = UsersDeleteUserDeleteApiV1UsersUserIdErrors[keyof UsersDeleteUserDeleteApiV1UsersUserIdErrors];

export type UsersDeleteUserDeleteApiV1UsersUserIdResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersDeleteUserDeleteApiV1UsersUserIdResponse = UsersDeleteUserDeleteApiV1UsersUserIdResponses[keyof UsersDeleteUserDeleteApiV1UsersUserIdResponses];

export type UsersReadUserByIdGetApiV1UsersUserIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersReadUserByIdGetApiV1UsersUserIdErrors = {
    /**
     * Bad Request
     */
    400: RefineErrorResponse;
    /**
     * Unauthorized
     */
    401: RefineErrorResponse;
    /**
     * Forbidden
     */
    403: RefineErrorResponse;
    /**
     * Not Found
     */
    404: RefineErrorResponse;
    /**
     * Conflict
     */
    409: RefineErrorResponse;
    /**
     * Validation Error
     */
    422: RefineErrorResponse;
    /**
     * Internal Server Error
     */
    500: RefineErrorResponse;
    /**
     * Service Unavailable
     */
    503: RefineErrorResponse;
};

export type UsersReadUserByIdGetApiV1UsersUserIdError = UsersReadUserByIdGetApiV1UsersUserIdErrors[keyof UsersReadUserByIdGetApiV1UsersUserIdErrors];

export type UsersReadUserByIdGetApiV1UsersUserIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersReadUserByIdGetApiV1UsersUserIdResponse = UsersReadUserByIdGetApiV1UsersUserIdResponses[keyof UsersReadUserByIdGetApiV1UsersUserIdResponses];

export type UsersUpdateUserPatchApiV1UsersUserIdData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersUpdateUserPatchApiV1UsersUserIdErrors = {
    /**
     * Bad Request
     */
    400: RefineErrorResponse;
    /**
     * Unauthorized
     */
    401: RefineErrorResponse;
    /**
     * Forbidden
     */
    403: RefineErrorResponse;
    /**
     * Not Found
     */
    404: RefineErrorResponse;
    /**
     * Conflict
     */
    409: RefineErrorResponse;
    /**
     * Validation Error
     */
    422: RefineErrorResponse;
    /**
     * Internal Server Error
     */
    500: RefineErrorResponse;
    /**
     * Service Unavailable
     */
    503: RefineErrorResponse;
};

export type UsersUpdateUserPatchApiV1UsersUserIdError = UsersUpdateUserPatchApiV1UsersUserIdErrors[keyof UsersUpdateUserPatchApiV1UsersUserIdErrors];

export type UsersUpdateUserPatchApiV1UsersUserIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersUpdateUserPatchApiV1UsersUserIdResponse = UsersUpdateUserPatchApiV1UsersUserIdResponses[keyof UsersUpdateUserPatchApiV1UsersUserIdResponses];

export type UsersReadUsersGetApiV1OwnersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         *  Start
         */
        _start?: number | null;
        /**
         *  End
         */
        _end?: number | null;
        /**
         *  Sort
         */
        _sort?: string | null;
        /**
         *  Order
         */
        _order?: string | null;
    };
    url: '/api/v1/owners/';
};

export type UsersReadUsersGetApiV1OwnersErrors = {
    /**
     * Bad Request
     */
    400: RefineErrorResponse;
    /**
     * Unauthorized
     */
    401: RefineErrorResponse;
    /**
     * Forbidden
     */
    403: RefineErrorResponse;
    /**
     * Not Found
     */
    404: RefineErrorResponse;
    /**
     * Conflict
     */
    409: RefineErrorResponse;
    /**
     * Validation Error
     */
    422: RefineErrorResponse;
    /**
     * Internal Server Error
     */
    500: RefineErrorResponse;
    /**
     * Service Unavailable
     */
    503: RefineErrorResponse;
};

export type UsersReadUsersGetApiV1OwnersError = UsersReadUsersGetApiV1OwnersErrors[keyof UsersReadUsersGetApiV1OwnersErrors];

export type UsersReadUsersGetApiV1OwnersResponses = {
    /**
     * Response Users Read Users Get Api V1 Owners
     * Successful Response
     */
    200: Array<UserPublic>;
};

export type UsersReadUsersGetApiV1OwnersResponse = UsersReadUsersGetApiV1OwnersResponses[keyof UsersReadUsersGetApiV1OwnersResponses];

export type UsersReadUserByIdGetApiV1OwnersUserIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/owners/{user_id}';
};

export type UsersReadUserByIdGetApiV1OwnersUserIdErrors = {
    /**
     * Bad Request
     */
    400: RefineErrorResponse;
    /**
     * Unauthorized
     */
    401: RefineErrorResponse;
    /**
     * Forbidden
     */
    403: RefineErrorResponse;
    /**
     * Not Found
     */
    404: RefineErrorResponse;
    /**
     * Conflict
     */
    409: RefineErrorResponse;
    /**
     * Validation Error
     */
    422: RefineErrorResponse;
    /**
     * Internal Server Error
     */
    500: RefineErrorResponse;
    /**
     * Service Unavailable
     */
    503: RefineErrorResponse;
};

export type UsersReadUserByIdGetApiV1OwnersUserIdError = UsersReadUserByIdGetApiV1OwnersUserIdErrors[keyof UsersReadUserByIdGetApiV1OwnersUserIdErrors];

export type UsersReadUserByIdGetApiV1OwnersUserIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersReadUserByIdGetApiV1OwnersUserIdResponse = UsersReadUserByIdGetApiV1OwnersUserIdResponses[keyof UsersReadUserByIdGetApiV1OwnersUserIdResponses];

export type UtilsTestEmailPostApiV1UtilsTestEmailData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email To
         */
        email_to: string;
    };
    url: '/api/v1/utils/test-email/';
};

export type UtilsTestEmailPostApiV1UtilsTestEmailErrors = {
    /**
     * Bad Request
     */
    400: RefineErrorResponse;
    /**
     * Unauthorized
     */
    401: RefineErrorResponse;
    /**
     * Forbidden
     */
    403: RefineErrorResponse;
    /**
     * Not Found
     */
    404: RefineErrorResponse;
    /**
     * Conflict
     */
    409: RefineErrorResponse;
    /**
     * Validation Error
     */
    422: RefineErrorResponse;
    /**
     * Internal Server Error
     */
    500: RefineErrorResponse;
    /**
     * Service Unavailable
     */
    503: RefineErrorResponse;
};

export type UtilsTestEmailPostApiV1UtilsTestEmailError = UtilsTestEmailPostApiV1UtilsTestEmailErrors[keyof UtilsTestEmailPostApiV1UtilsTestEmailErrors];

export type UtilsTestEmailPostApiV1UtilsTestEmailResponses = {
    /**
     * Successful Response
     */
    201: Message;
};

export type UtilsTestEmailPostApiV1UtilsTestEmailResponse = UtilsTestEmailPostApiV1UtilsTestEmailResponses[keyof UtilsTestEmailPostApiV1UtilsTestEmailResponses];

export type UtilsHealthCheckGetApiV1UtilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type UtilsHealthCheckGetApiV1UtilsHealthCheckErrors = {
    /**
     * Bad Request
     */
    400: RefineErrorResponse;
    /**
     * Unauthorized
     */
    401: RefineErrorResponse;
    /**
     * Forbidden
     */
    403: RefineErrorResponse;
    /**
     * Not Found
     */
    404: RefineErrorResponse;
    /**
     * Conflict
     */
    409: RefineErrorResponse;
    /**
     * Validation Error
     */
    422: RefineErrorResponse;
    /**
     * Internal Server Error
     */
    500: RefineErrorResponse;
    /**
     * Service Unavailable
     */
    503: RefineErrorResponse;
};

export type UtilsHealthCheckGetApiV1UtilsHealthCheckError = UtilsHealthCheckGetApiV1UtilsHealthCheckErrors[keyof UtilsHealthCheckGetApiV1UtilsHealthCheckErrors];

export type UtilsHealthCheckGetApiV1UtilsHealthCheckResponses = {
    /**
     * Response Utils Health Check Get Api V1 Utils Health Check
     * Successful Response
     */
    200: boolean;
};

export type UtilsHealthCheckGetApiV1UtilsHealthCheckResponse = UtilsHealthCheckGetApiV1UtilsHealthCheckResponses[keyof UtilsHealthCheckGetApiV1UtilsHealthCheckResponses];

export type ItemsReadItemsGetApiV1ItemsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         *  Start
         */
        _start?: number | null;
        /**
         *  End
         */
        _end?: number | null;
        /**
         *  Sort
         */
        _sort?: string | null;
        /**
         *  Order
         */
        _order?: string | null;
    };
    url: '/api/v1/items/';
};

export type ItemsReadItemsGetApiV1ItemsErrors = {
    /**
     * Bad Request
     */
    400: RefineErrorResponse;
    /**
     * Unauthorized
     */
    401: RefineErrorResponse;
    /**
     * Forbidden
     */
    403: RefineErrorResponse;
    /**
     * Not Found
     */
    404: RefineErrorResponse;
    /**
     * Conflict
     */
    409: RefineErrorResponse;
    /**
     * Validation Error
     */
    422: RefineErrorResponse;
    /**
     * Internal Server Error
     */
    500: RefineErrorResponse;
    /**
     * Service Unavailable
     */
    503: RefineErrorResponse;
};

export type ItemsReadItemsGetApiV1ItemsError = ItemsReadItemsGetApiV1ItemsErrors[keyof ItemsReadItemsGetApiV1ItemsErrors];

export type ItemsReadItemsGetApiV1ItemsResponses = {
    /**
     * Response Items Read Items Get Api V1 Items
     * Successful Response
     */
    200: Array<ItemPublic>;
};

export type ItemsReadItemsGetApiV1ItemsResponse = ItemsReadItemsGetApiV1ItemsResponses[keyof ItemsReadItemsGetApiV1ItemsResponses];

export type ItemsCreateItemPostApiV1ItemsData = {
    body: ItemCreate;
    path?: never;
    query?: never;
    url: '/api/v1/items/';
};

export type ItemsCreateItemPostApiV1ItemsErrors = {
    /**
     * Bad Request
     */
    400: RefineErrorResponse;
    /**
     * Unauthorized
     */
    401: RefineErrorResponse;
    /**
     * Forbidden
     */
    403: RefineErrorResponse;
    /**
     * Not Found
     */
    404: RefineErrorResponse;
    /**
     * Conflict
     */
    409: RefineErrorResponse;
    /**
     * Validation Error
     */
    422: RefineErrorResponse;
    /**
     * Internal Server Error
     */
    500: RefineErrorResponse;
    /**
     * Service Unavailable
     */
    503: RefineErrorResponse;
};

export type ItemsCreateItemPostApiV1ItemsError = ItemsCreateItemPostApiV1ItemsErrors[keyof ItemsCreateItemPostApiV1ItemsErrors];

export type ItemsCreateItemPostApiV1ItemsResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type ItemsCreateItemPostApiV1ItemsResponse = ItemsCreateItemPostApiV1ItemsResponses[keyof ItemsCreateItemPostApiV1ItemsResponses];

export type ItemsDeleteItemDeleteApiV1ItemsIdData = {
    body?: never;
    path: {
        /**
         * Id
         * The item ID
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type ItemsDeleteItemDeleteApiV1ItemsIdErrors = {
    /**
     * Bad Request
     */
    400: RefineErrorResponse;
    /**
     * Unauthorized
     */
    401: RefineErrorResponse;
    /**
     * Forbidden
     */
    403: RefineErrorResponse;
    /**
     * Not Found
     */
    404: RefineErrorResponse;
    /**
     * Conflict
     */
    409: RefineErrorResponse;
    /**
     * Validation Error
     */
    422: RefineErrorResponse;
    /**
     * Internal Server Error
     */
    500: RefineErrorResponse;
    /**
     * Service Unavailable
     */
    503: RefineErrorResponse;
};

export type ItemsDeleteItemDeleteApiV1ItemsIdError = ItemsDeleteItemDeleteApiV1ItemsIdErrors[keyof ItemsDeleteItemDeleteApiV1ItemsIdErrors];

export type ItemsDeleteItemDeleteApiV1ItemsIdResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type ItemsDeleteItemDeleteApiV1ItemsIdResponse = ItemsDeleteItemDeleteApiV1ItemsIdResponses[keyof ItemsDeleteItemDeleteApiV1ItemsIdResponses];

export type ItemsReadItemGetApiV1ItemsIdData = {
    body?: never;
    path: {
        /**
         * Id
         * The item ID
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type ItemsReadItemGetApiV1ItemsIdErrors = {
    /**
     * Bad Request
     */
    400: RefineErrorResponse;
    /**
     * Unauthorized
     */
    401: RefineErrorResponse;
    /**
     * Forbidden
     */
    403: RefineErrorResponse;
    /**
     * Not Found
     */
    404: RefineErrorResponse;
    /**
     * Conflict
     */
    409: RefineErrorResponse;
    /**
     * Validation Error
     */
    422: RefineErrorResponse;
    /**
     * Internal Server Error
     */
    500: RefineErrorResponse;
    /**
     * Service Unavailable
     */
    503: RefineErrorResponse;
};

export type ItemsReadItemGetApiV1ItemsIdError = ItemsReadItemGetApiV1ItemsIdErrors[keyof ItemsReadItemGetApiV1ItemsIdErrors];

export type ItemsReadItemGetApiV1ItemsIdResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type ItemsReadItemGetApiV1ItemsIdResponse = ItemsReadItemGetApiV1ItemsIdResponses[keyof ItemsReadItemGetApiV1ItemsIdResponses];

export type ItemsUpdateItemPatchApiV1ItemsIdData = {
    body: ItemUpdate;
    path: {
        /**
         * Id
         * The item ID
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type ItemsUpdateItemPatchApiV1ItemsIdErrors = {
    /**
     * Bad Request
     */
    400: RefineErrorResponse;
    /**
     * Unauthorized
     */
    401: RefineErrorResponse;
    /**
     * Forbidden
     */
    403: RefineErrorResponse;
    /**
     * Not Found
     */
    404: RefineErrorResponse;
    /**
     * Conflict
     */
    409: RefineErrorResponse;
    /**
     * Validation Error
     */
    422: RefineErrorResponse;
    /**
     * Internal Server Error
     */
    500: RefineErrorResponse;
    /**
     * Service Unavailable
     */
    503: RefineErrorResponse;
};

export type ItemsUpdateItemPatchApiV1ItemsIdError = ItemsUpdateItemPatchApiV1ItemsIdErrors[keyof ItemsUpdateItemPatchApiV1ItemsIdErrors];

export type ItemsUpdateItemPatchApiV1ItemsIdResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type ItemsUpdateItemPatchApiV1ItemsIdResponse = ItemsUpdateItemPatchApiV1ItemsIdResponses[keyof ItemsUpdateItemPatchApiV1ItemsIdResponses];

export type ItemsUpdateItemPutApiV1ItemsIdData = {
    body: ItemUpdate;
    path: {
        /**
         * Id
         * The item ID
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type ItemsUpdateItemPutApiV1ItemsIdErrors = {
    /**
     * Bad Request
     */
    400: RefineErrorResponse;
    /**
     * Unauthorized
     */
    401: RefineErrorResponse;
    /**
     * Forbidden
     */
    403: RefineErrorResponse;
    /**
     * Not Found
     */
    404: RefineErrorResponse;
    /**
     * Conflict
     */
    409: RefineErrorResponse;
    /**
     * Validation Error
     */
    422: RefineErrorResponse;
    /**
     * Internal Server Error
     */
    500: RefineErrorResponse;
    /**
     * Service Unavailable
     */
    503: RefineErrorResponse;
};

export type ItemsUpdateItemPutApiV1ItemsIdError = ItemsUpdateItemPutApiV1ItemsIdErrors[keyof ItemsUpdateItemPutApiV1ItemsIdErrors];

export type ItemsUpdateItemPutApiV1ItemsIdResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type ItemsUpdateItemPutApiV1ItemsIdResponse = ItemsUpdateItemPutApiV1ItemsIdResponses[keyof ItemsUpdateItemPutApiV1ItemsIdResponses];

export type AssetsReadAssetsGetApiV1AssetsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         *  Start
         */
        _start?: number | null;
        /**
         *  End
         */
        _end?: number | null;
        /**
         *  Sort
         */
        _sort?: string | null;
        /**
         *  Order
         */
        _order?: string | null;
    };
    url: '/api/v1/assets/';
};

export type AssetsReadAssetsGetApiV1AssetsErrors = {
    /**
     * Bad Request
     */
    400: RefineErrorResponse;
    /**
     * Unauthorized
     */
    401: RefineErrorResponse;
    /**
     * Forbidden
     */
    403: RefineErrorResponse;
    /**
     * Not Found
     */
    404: RefineErrorResponse;
    /**
     * Conflict
     */
    409: RefineErrorResponse;
    /**
     * Validation Error
     */
    422: RefineErrorResponse;
    /**
     * Internal Server Error
     */
    500: RefineErrorResponse;
    /**
     * Service Unavailable
     */
    503: RefineErrorResponse;
};

export type AssetsReadAssetsGetApiV1AssetsError = AssetsReadAssetsGetApiV1AssetsErrors[keyof AssetsReadAssetsGetApiV1AssetsErrors];

export type AssetsReadAssetsGetApiV1AssetsResponses = {
    /**
     * Response Assets Read Assets Get Api V1 Assets
     * Successful Response
     */
    200: Array<AssetPublic>;
};

export type AssetsReadAssetsGetApiV1AssetsResponse = AssetsReadAssetsGetApiV1AssetsResponses[keyof AssetsReadAssetsGetApiV1AssetsResponses];

export type AssetsCreateAssetUploadUrlPostApiV1AssetsPresignedUploadData = {
    body: AssetPresignedUploadRequest;
    path?: never;
    query?: never;
    url: '/api/v1/assets/presigned-upload';
};

export type AssetsCreateAssetUploadUrlPostApiV1AssetsPresignedUploadErrors = {
    /**
     * Bad Request
     */
    400: RefineErrorResponse;
    /**
     * Unauthorized
     */
    401: RefineErrorResponse;
    /**
     * Forbidden
     */
    403: RefineErrorResponse;
    /**
     * Not Found
     */
    404: RefineErrorResponse;
    /**
     * Conflict
     */
    409: RefineErrorResponse;
    /**
     * Validation Error
     */
    422: RefineErrorResponse;
    /**
     * Internal Server Error
     */
    500: RefineErrorResponse;
    /**
     * Service Unavailable
     */
    503: RefineErrorResponse;
};

export type AssetsCreateAssetUploadUrlPostApiV1AssetsPresignedUploadError = AssetsCreateAssetUploadUrlPostApiV1AssetsPresignedUploadErrors[keyof AssetsCreateAssetUploadUrlPostApiV1AssetsPresignedUploadErrors];

export type AssetsCreateAssetUploadUrlPostApiV1AssetsPresignedUploadResponses = {
    /**
     * Successful Response
     */
    200: AssetPresignedUploadResponse;
};

export type AssetsCreateAssetUploadUrlPostApiV1AssetsPresignedUploadResponse = AssetsCreateAssetUploadUrlPostApiV1AssetsPresignedUploadResponses[keyof AssetsCreateAssetUploadUrlPostApiV1AssetsPresignedUploadResponses];

export type AssetsDeleteAssetDeleteApiV1AssetsIdData = {
    body?: never;
    path: {
        /**
         * Id
         * The asset ID
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/assets/{id}';
};

export type AssetsDeleteAssetDeleteApiV1AssetsIdErrors = {
    /**
     * Bad Request
     */
    400: RefineErrorResponse;
    /**
     * Unauthorized
     */
    401: RefineErrorResponse;
    /**
     * Forbidden
     */
    403: RefineErrorResponse;
    /**
     * Not Found
     */
    404: RefineErrorResponse;
    /**
     * Conflict
     */
    409: RefineErrorResponse;
    /**
     * Validation Error
     */
    422: RefineErrorResponse;
    /**
     * Internal Server Error
     */
    500: RefineErrorResponse;
    /**
     * Service Unavailable
     */
    503: RefineErrorResponse;
};

export type AssetsDeleteAssetDeleteApiV1AssetsIdError = AssetsDeleteAssetDeleteApiV1AssetsIdErrors[keyof AssetsDeleteAssetDeleteApiV1AssetsIdErrors];

export type AssetsDeleteAssetDeleteApiV1AssetsIdResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type AssetsDeleteAssetDeleteApiV1AssetsIdResponse = AssetsDeleteAssetDeleteApiV1AssetsIdResponses[keyof AssetsDeleteAssetDeleteApiV1AssetsIdResponses];

export type AssetsReadAssetGetApiV1AssetsIdData = {
    body?: never;
    path: {
        /**
         * Id
         * The asset ID
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/assets/{id}';
};

export type AssetsReadAssetGetApiV1AssetsIdErrors = {
    /**
     * Bad Request
     */
    400: RefineErrorResponse;
    /**
     * Unauthorized
     */
    401: RefineErrorResponse;
    /**
     * Forbidden
     */
    403: RefineErrorResponse;
    /**
     * Not Found
     */
    404: RefineErrorResponse;
    /**
     * Conflict
     */
    409: RefineErrorResponse;
    /**
     * Validation Error
     */
    422: RefineErrorResponse;
    /**
     * Internal Server Error
     */
    500: RefineErrorResponse;
    /**
     * Service Unavailable
     */
    503: RefineErrorResponse;
};

export type AssetsReadAssetGetApiV1AssetsIdError = AssetsReadAssetGetApiV1AssetsIdErrors[keyof AssetsReadAssetGetApiV1AssetsIdErrors];

export type AssetsReadAssetGetApiV1AssetsIdResponses = {
    /**
     * Successful Response
     */
    200: AssetPublic;
};

export type AssetsReadAssetGetApiV1AssetsIdResponse = AssetsReadAssetGetApiV1AssetsIdResponses[keyof AssetsReadAssetGetApiV1AssetsIdResponses];

export type AssetsUpdateAssetPatchApiV1AssetsIdData = {
    body: AssetUpdate;
    path: {
        /**
         * Id
         * The asset ID
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/assets/{id}';
};

export type AssetsUpdateAssetPatchApiV1AssetsIdErrors = {
    /**
     * Bad Request
     */
    400: RefineErrorResponse;
    /**
     * Unauthorized
     */
    401: RefineErrorResponse;
    /**
     * Forbidden
     */
    403: RefineErrorResponse;
    /**
     * Not Found
     */
    404: RefineErrorResponse;
    /**
     * Conflict
     */
    409: RefineErrorResponse;
    /**
     * Validation Error
     */
    422: RefineErrorResponse;
    /**
     * Internal Server Error
     */
    500: RefineErrorResponse;
    /**
     * Service Unavailable
     */
    503: RefineErrorResponse;
};

export type AssetsUpdateAssetPatchApiV1AssetsIdError = AssetsUpdateAssetPatchApiV1AssetsIdErrors[keyof AssetsUpdateAssetPatchApiV1AssetsIdErrors];

export type AssetsUpdateAssetPatchApiV1AssetsIdResponses = {
    /**
     * Successful Response
     */
    200: AssetPublic;
};

export type AssetsUpdateAssetPatchApiV1AssetsIdResponse = AssetsUpdateAssetPatchApiV1AssetsIdResponses[keyof AssetsUpdateAssetPatchApiV1AssetsIdResponses];

export type AssetsReadAssetDownloadUrlGetApiV1AssetsIdDownloadUrlData = {
    body?: never;
    path: {
        /**
         * Id
         * The asset ID
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/assets/{id}/download-url';
};

export type AssetsReadAssetDownloadUrlGetApiV1AssetsIdDownloadUrlErrors = {
    /**
     * Bad Request
     */
    400: RefineErrorResponse;
    /**
     * Unauthorized
     */
    401: RefineErrorResponse;
    /**
     * Forbidden
     */
    403: RefineErrorResponse;
    /**
     * Not Found
     */
    404: RefineErrorResponse;
    /**
     * Conflict
     */
    409: RefineErrorResponse;
    /**
     * Validation Error
     */
    422: RefineErrorResponse;
    /**
     * Internal Server Error
     */
    500: RefineErrorResponse;
    /**
     * Service Unavailable
     */
    503: RefineErrorResponse;
};

export type AssetsReadAssetDownloadUrlGetApiV1AssetsIdDownloadUrlError = AssetsReadAssetDownloadUrlGetApiV1AssetsIdDownloadUrlErrors[keyof AssetsReadAssetDownloadUrlGetApiV1AssetsIdDownloadUrlErrors];

export type AssetsReadAssetDownloadUrlGetApiV1AssetsIdDownloadUrlResponses = {
    /**
     * Successful Response
     */
    200: AssetPresignedDownloadResponse;
};

export type AssetsReadAssetDownloadUrlGetApiV1AssetsIdDownloadUrlResponse = AssetsReadAssetDownloadUrlGetApiV1AssetsIdDownloadUrlResponses[keyof AssetsReadAssetDownloadUrlGetApiV1AssetsIdDownloadUrlResponses];

export type PrivateCreateUserPostApiV1PrivateUsersData = {
    body: PrivateUserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/private/users/';
};

export type PrivateCreateUserPostApiV1PrivateUsersErrors = {
    /**
     * Bad Request
     */
    400: RefineErrorResponse;
    /**
     * Unauthorized
     */
    401: RefineErrorResponse;
    /**
     * Forbidden
     */
    403: RefineErrorResponse;
    /**
     * Not Found
     */
    404: RefineErrorResponse;
    /**
     * Conflict
     */
    409: RefineErrorResponse;
    /**
     * Validation Error
     */
    422: RefineErrorResponse;
    /**
     * Internal Server Error
     */
    500: RefineErrorResponse;
    /**
     * Service Unavailable
     */
    503: RefineErrorResponse;
};

export type PrivateCreateUserPostApiV1PrivateUsersError = PrivateCreateUserPostApiV1PrivateUsersErrors[keyof PrivateCreateUserPostApiV1PrivateUsersErrors];

export type PrivateCreateUserPostApiV1PrivateUsersResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type PrivateCreateUserPostApiV1PrivateUsersResponse = PrivateCreateUserPostApiV1PrivateUsersResponses[keyof PrivateCreateUserPostApiV1PrivateUsersResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};